import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Checkout - Pay With Crypto",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
    shortcut: "/favicon.png",
    apple: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          id="clarity-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){ 
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)}; 
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i; 
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y); 
              })(window, document, "clarity", "script", "ttm0mrcdpc");
            `,
          }}
        />
      </head>
      <body
        className={`${inter.variable} font-inter antialiased`}
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
