import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { TranslationProvider } from "./contexts/TranslationContext";
import { CurrencyProvider } from "./contexts/CurrencyContext";
import "./globals.css";
import "flag-icons/css/flag-icons.min.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Checkout - Pay With Crypto",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
    apple: "/favicon.ico",
  },
  other: {
    'google': 'notranslate',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no">
      <head>
        <Script
          id="clarity-script"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(c,l,a,r,i,t,y){ 
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)}; 
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i; 
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y); 
              })(window, document, "clarity", "script", "ttm0mrcdpc");
            `,
          }}
        />
      </head>
      <body
        className={`${inter.variable} font-inter antialiased`}
        suppressHydrationWarning={true}
        translate="no"
      >
        <TranslationProvider>
          <CurrencyProvider>
            {children}
          </CurrencyProvider>
        </TranslationProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
